version = 1

# Exclude generated DB code
exclude_patterns = [
    "server/main/kotlin/ch/yass/db/**",
    "client/**",
    "webclient/**",
    "http/**"
]

[[analyzers]]
name = "kotlin"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true