version: '3.8'
services:
  db-test:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres-test
      - POSTGRES_PASSWORD=postgres-test
      - POSTGRES_DB=yass-test
    ports:
      - '5433:5432'
  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=yass
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  kratos-migrate:
    depends_on:
      - db
    image: oryd/kratos:v0.11.0
    environment:
      - DSN=postgres://postgres:postgres@db:5432/yass
    volumes:
      - type: bind
        source: ./.docker/kratos/email-password
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes

  kratos-self-service-ui-node:
    depends_on:
      - kratos-migrate
    image: oryd/kratos-selfservice-ui-node:v0.11.0
    environment:
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_BROWSER_URL=http://127.0.0.1:4433/
    ports:
      - '4455:3000'

  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.11.0
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    environment:
      - DSN=postgres://postgres:postgres@db:5432/yass
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: bind
        source: ./.docker/kratos/email-password
        target: /etc/config/kratos

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'

volumes:
  db:
    driver: local