version: '3.8'
services:
  db-test:
    image: postgres:15.4-alpine
    environment:
      - POSTGRES_USER=postgres-test
      - POSTGRES_PASSWORD=postgres-test
      - POSTGRES_DB=yass-test
    ports:
      - '5433:5432'
  db:
    image: postgres:15.4-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=yass
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  kratos-migrate:
    depends_on:
      - db
    image: oryd/kratos:v1.1.0
    environment:
      - DSN=postgres://postgres:postgres@db:5432/yass
    volumes:
      - type: bind
        source: ./.docker/kratos/email-password
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes

  kratos-self-service-ui-node:
    depends_on:
      - kratos-migrate
    image: oryd/kratos-selfservice-ui-node:v1.1.0
    environment:
      - KRATOS_PUBLIC_URL=http://127.0.0.1:4433/
      - KRATOS_BROWSER_URL=http://127.0.0.1:4433/
      - COOKIE_SECRET=changeme
      - CSRF_COOKIE_NAME=ory_csrf_ui
      - CSRF_COOKIE_SECRET=changeme
    ports:
      - '4455:3000'

  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v1.1.0
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    environment:
      - DSN=postgres://postgres:postgres@db:5432/yass
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: bind
        source: ./.docker/kratos/email-password
        target: /etc/config/kratos

  centrifugo:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: centrifugo
    image: centrifugo/centrifugo:v5.2
    volumes:
      - ./.docker/centrifugo/config.json:/centrifugo/config.json
    command: centrifugo -c config.json
    ports:
      - '8000:8000'
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'

volumes:
  db:
    driver: local